---
title: "Assignment 2"
subtitle: "Almond Yield"
date: last-modified
author: "Kyle Alves & Steven Mitchell"
format: 
  html:
    code-fold: true
    toc: true
    toc-location: left
    theme: sandstone
    background-color: "#f8f9fa"
execute:
  echo: true
  warning: false
  message: false
editor: visual
---

# The Almond Yield Equation from Lobell et al. 2006

$$
Y = -0.015T_{n,2} - 0.0046T^{2}_{n,2} - 0.07P_{1} + 0.0043P^{2}_{1} + 0.28
$$

```{r libraries}
library(tidyverse)
library(here)
library(janitor)
```

### Data wrangling

```{r data}
clim_data <- read_delim(file = "clim.txt", delim = " ") |>
  group_by(year, month) %>%
  summarise(T = min(tmin_c),
            P = sum(precip))

T <- clim_data %>% 
  filter(month == 2) %>% 
  select(year, T)

P <- clim_data %>%
  filter(month == 1) %>% 
  select(year, P)
```

```{r}
clim_clean = data.frame(temp=T, precip=P) |>
  clean_names() |>
  select(-precip_year) |>
  rename(year = temp_year) |>
  rename(temp = temp_t) |>
  rename(precip = precip_p)
```

```{r}
source(here("R", "almond-yield.R"))
```

### Exploratory Data Analysis

```{r}
dailyprecip <- ggplot(data = clim_clean) +
  geom_col(aes(x = year, y = precip), color = "blue") +
  labs(title = "Daily Precipitation in January", x = "Date", y = "Precipitation (mm)") +
  theme_minimal()

dailyprecip
```

```{r}
dailytemp <- ggplot(data = clim_clean) +
  geom_col(aes(x = year, y = temp), color = "blue") +
  labs(title = "Daily Temperature in January", x = "Date", y = "Temperature (C)") +
  theme_minimal()

dailytemp
```

### Apply Model on Data

```{r}
clim_clean$ayield = almondyield(clim_clean$temp, clim_clean$precip)

#find the maximum, minimum and mean yield anomoly
max_yield = max(clim_clean$ayield)
min_yield = min(clim_clean$ayield)
mean_yield = mean(clim_clean$ayield)

tibble(max_yield, min_yield, mean_yield)
```
